"""
Generate a QuantConnect-ready uploader with embedded fundamental CSV data.

Reads from quantconnect/fundamental_data/*.csv and produces
quantconnect/UPLOAD_FUNDAMENTALS_READY.py with all data embedded.
"""

import os
import glob

FUND_DIR = "/Users/MBP/Desktop/Project_Asset_Shield/quantconnect/fundamental_data"
OUTPUT = "/Users/MBP/Desktop/Project_Asset_Shield/quantconnect/UPLOAD_FUNDAMENTALS_READY.py"

HEADER = '''# region imports
from AlgorithmImports import *
# endregion


class FundamentalDataUploader(QCAlgorithm):
    """
    Upload all 50 stocks' fundamental data to ObjectStore.
    Auto-generated by generate_fund_uploader.py
    """

    def Initialize(self):
        self.SetStartDate(2024, 1, 1)
        self.SetEndDate(2024, 1, 2)
        self.SetCash(1000)

        FUNDAMENTAL_DATA = {
'''

FOOTER = '''        }

        uploaded = 0
        for code, csv_data in FUNDAMENTAL_DATA.items():
            if csv_data.strip():
                key = f"japan_fundamentals/{code}.csv"
                self.ObjectStore.Save(key, csv_data.strip())
                lines = len(csv_data.strip().split('\\n'))
                self.Debug(f"Uploaded: {key} ({lines} records)")
                uploaded += 1

        self.Debug("=" * 60)
        self.Debug(f"Fundamental upload complete: {uploaded} stocks")
        self.Debug("=" * 60)

    def OnData(self, data):
        pass
'''


def main():
    csv_files = sorted(glob.glob(os.path.join(FUND_DIR, "*.csv")))

    if not csv_files:
        print(f"No CSV files in {FUND_DIR}")
        return

    parts = []
    total_records = 0

    for csv_path in csv_files:
        code = os.path.basename(csv_path).replace(".csv", "")
        with open(csv_path) as f:
            content = f.read().strip()
        lines = len(content.split("\n"))
        total_records += lines

        # Escape any triple quotes in data (unlikely but safe)
        content = content.replace('"""', '\\"\\"\\"')
        parts.append(f'            "{code}": """{content}""",\n')

    with open(OUTPUT, "w") as f:
        f.write(HEADER)
        for part in parts:
            f.write(part)
        f.write(FOOTER)

    print(f"Generated: {OUTPUT}")
    print(f"Stocks: {len(csv_files)}, Records: {total_records}")
    file_size = os.path.getsize(OUTPUT)
    print(f"File size: {file_size:,} bytes ({file_size / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
